[project]
name = "python-scraper"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "fastapi[standard]>=0.115.9",
    "pytz>=2025.1",
    "requests>=2.32.3",
    "selenium>=4.29.0",
]
