import {
  AllMatchResults,
  AllUpcomingMatchesData,
  SingleLiveMatchData,
  SingleMatchResult,
  SingleUpcomingMatchData,
} from './types.js';

export const allUpcomingMatchesData: AllUpcomingMatchesData = {
  'data': {
    'status': 200,
    'segments': [
      {
        'team1': 'Cubert Academy',
        'team2': 'ENVY',
        'match_page':
          'https://www.vlr.gg/459085/cubert-academy-vs-envy-challengers-league-2025-north-america-ace-stage-1-playoffs-lr2',
      },
      {
        'team1': 'MIX',
        'team2': 'Zen eSports GC',
        'match_page':
          'https://www.vlr.gg/454602/mix-vs-zen-esports-gc-game-changers-2025-latam-south-stage-1-w4',
      },
      {
        'team1': 'University War GC',
        'team2': 'Prasso Clan',
        'match_page':
          'https://www.vlr.gg/454603/university-war-gc-vs-prasso-clan-game-changers-2025-latam-south-stage-1-w4',
      },
    ],
  },
};

export const singleUpcomingMatchData: SingleUpcomingMatchData = {
  'data': {
    'status': 200,
    'segments': [
      {
        'team1': 'Reckoning Esports',
        'team2': 'Revenant XSpark',
        'logo1': '//owcdn.net/img/5f7b4a299fe14.png',
        'logo2': '//owcdn.net/img/6780c7e474266.png',
        'team1_short': 'RGE',
        'team2_short': 'RNTX',
        'players1': [
          {
            'id': 1,
            'name': 'Deadly10',
            'flag': 'flag-in',
          },
          {
            'id': 2,
            'name': 'Bgg',
            'flag': 'flag-ru',
          },
          {
            'id': 3,
            'name': 'moner',
            'flag': 'flag-ru',
          },
          {
            'id': 4,
            'name': 'tricky',
            'flag': 'flag-in',
          },
          {
            'id': 5,
            'name': 'Ri0',
            'flag': 'flag-in',
          },
        ],
        'players2': [
          {
            'id': 1,
            'name': 'Antidote',
            'flag': 'flag-in',
          },
          {
            'id': 2,
            'name': 'DEATHMAKER',
            'flag': 'flag-in',
          },
          {
            'id': 3,
            'name': 'rawfiul',
            'flag': 'flag-in',
          },
          {
            'id': 4,
            'name': 'azys',
            'flag': 'flag-ph',
          },
          {
            'id': 5,
            'name': 'Georggyyy',
            'flag': 'flag-ph',
          },
        ],
        'match_series': 'Challengers League 2025 South Asia: Split 1',
        'match_event': 'Main Event: Week 3',
        'event_logo': '//owcdn.net/img/6009f963577f4.png',
        'match_date': 'Tuesday, March 18th',
        'match_time': '9:30 AM UTC',
        'unix_timestamp': '2025-03-18 09:30:00',
        'rounds': 'Bo3',
      },
    ],
  },
};

export const liveMatchData: SingleLiveMatchData = {
  'data': {
    'status': 200,
    'segments': [
      {
        'team1': 'AURA',
        'team2': 'Orangutan',
        'logo1': '//owcdn.net/img/67beced893e25.png',
        'logo2': '//owcdn.net/img/65f6a278338a3.png',
        'match_series': 'Challengers League 2025 South Asia: Split 1',
        'match_event': 'Main Event: Week 3',
        'event_logo': '//owcdn.net/img/6009f963577f4.png',
        'match_date': 'Monday, March 17th',
        'match_time': '9:30 AM UTC',
        'team1_score': '0',
        'team2_score': '0',
        'rounds': [
          {
            'round': '1',
            'map_name': 'Haven',
            'map_duration': '-',
            'team1_round_score': '0',
            'team2_round_score': '0',
          },
          {
            'round': '2',
            'map_name': 'Split',
            'map_duration': '-',
            'team1_round_score': '0',
            'team2_round_score': '0',
          },
          {
            'round': '3',
            'map_name': 'Bind',
            'map_duration': '-',
            'team1_round_score': '0',
            'team2_round_score': '0',
          },
        ],
      },
    ],
  },
};

export const allMatchesResults: AllMatchResults = {
  'data': {
    'status': 200,
    'segments': [
      {
        'team1': 'Akave Esports GC',
        'team2': '1UP Festival Esports',
        'score1': '2',
        'score2': '0',
        'match_page':
          'https://www.vlr.gg/454635/akave-esports-gc-vs-1up-festival-esports-game-changers-2025-latam-north-stage-1-w4',
      },
      {
        'team1': 'Burger Boyz',
        'team2': 'Blue Otter',
        'score1': '2',
        'score2': '1',
        'match_page':
          'https://www.vlr.gg/460789/burger-boyz-vs-blue-otter-spike-drop-4-momentum-series-gf',
      },
      {
        'team1': 'No Sweat Blossom',
        'team2': 'FUSION X',
        'score1': '0',
        'score2': '2',
        'match_page':
          'https://www.vlr.gg/454633/no-sweat-blossom-vs-fusion-x-game-changers-2025-latam-north-stage-1-w4',
      },
      {
        'team1': 'BAAM Esports',
        'team2': 'One More Esports',
        'score1': '2',
        'score2': '1',
        'match_page':
          'https://www.vlr.gg/459557/baam-esports-vs-one-more-esports-challengers-league-2025-mena-resilience-north-africa-and-levant',
      },
      {
        'team1': 'Landor',
        'team2': 'Burger Boyz',
        'score1': '1',
        'score2': '2',
        'match_page':
          'https://www.vlr.gg/460787/landor-vs-burger-boyz-spike-drop-4-momentum-series-sf',
      },
    ],
  },
};

export const singleMatchResult: SingleMatchResult = {
  'data': {
    'status': 200,
    'segments': [
      {
        'team1': 'Winthrop University',
        'team2': 'M80',
        'logo1': '//owcdn.net/img/636c2f2592313.png',
        'logo2': '//owcdn.net/img/6793c97263739.png',
        'match_series': 'Challengers League 2025 North America ACE: Stage 1',
        'match_event': 'Playoffs: Lower Final',
        'event_logo': '//owcdn.net/img/63cbac52cf906.png',
        'team1_score': '2',
        'team2_score': '3',
        'team_picks':
          'M80 ban Bind; WU ban Split; M80 pick Lotus; WU pick Haven; M80 pick Abyss; WU pick Pearl; Fracture remains',
        'rounds': [
          {
            'round': 'all',
            'map_name': null,
            'map_duration': null,
            'team1_round_score': null,
            'team2_round_score': null,
            'team1_stats': [
              {
                'name': 'moobs',
                'flag': 'flag-ca',
                'agents': ['Cypher', 'Vyse'],
                'rating': '1.16',
                'acs': '254',
                'k': '113',
                'd': '95',
                'a': '20',
                'diff_k_d': '+18',
                'kast': '64%',
                'adr': '163',
                'hs': '41%',
                'fk': '18',
                'fd': '11',
                'diff_fk_fd': '+7',
              },
              {
                'name': 'flare',
                'flag': 'flag-vn',
                'agents': ['Tejo'],
                'rating': '0.98',
                'acs': '173',
                'k': '80',
                'd': '81',
                'a': '29',
                'diff_k_d': '-1',
                'kast': '72%',
                'adr': '129',
                'hs': '27%',
                'fk': '11',
                'fd': '4',
                'diff_fk_fd': '+7',
              },
              {
                'name': 'Ali',
                'flag': 'flag-ps',
                'agents': ['Clove', 'Astra', 'Brimstone'],
                'rating': '0.95',
                'acs': '191',
                'k': '80',
                'd': '91',
                'a': '42',
                'diff_k_d': '-11',
                'kast': '72%',
                'adr': '126',
                'hs': '29%',
                'fk': '3',
                'fd': '10',
                'diff_fk_fd': '-7',
              },
              {
                'name': 'Nahsie',
                'flag': 'flag-us',
                'agents': ['Sova', 'Breach', 'Fade'],
                'rating': '0.91',
                'acs': '180',
                'k': '70',
                'd': '88',
                'a': '58',
                'diff_k_d': '-18',
                'kast': '73%',
                'adr': '123',
                'hs': '29%',
                'fk': '5',
                'fd': '9',
                'diff_fk_fd': '-4',
              },
              {
                'name': 'infiltrator',
                'flag': 'flag-vn',
                'agents': ['Raze', 'Yoru', 'Jett'],
                'rating': '0.85',
                'acs': '180',
                'k': '81',
                'd': '92',
                'a': '18',
                'diff_k_d': '-11',
                'kast': '68%',
                'adr': '117',
                'hs': '23%',
                'fk': '29',
                'fd': '24',
                'diff_fk_fd': '+5',
              },
            ],
            'team2_stats': [
              {
                'name': 'bao',
                'flag': 'flag-vn',
                'agents': ['Vyse', 'Cypher', 'Astra', 'Killjoy'],
                'rating': '1.22',
                'acs': '233',
                'k': '108',
                'd': '84',
                'a': '27',
                'diff_k_d': '+24',
                'kast': '80%',
                'adr': '155',
                'hs': '32%',
                'fk': '9',
                'fd': '8',
                'diff_fk_fd': '+1',
              },
              {
                'name': 'bdog',
                'flag': 'flag-us',
                'agents': ['Omen', 'Astra', 'Brimstone'],
                'rating': '1.10',
                'acs': '204',
                'k': '89',
                'd': '83',
                'a': '67',
                'diff_k_d': '+6',
                'kast': '74%',
                'adr': '128',
                'hs': '29%',
                'fk': '11',
                'fd': '14',
                'diff_fk_fd': '-3',
              },
              {
                'name': 'Sato',
                'flag': 'flag-br',
                'agents': ['Raze', 'Neon', 'Jett'],
                'rating': '1.01',
                'acs': '234',
                'k': '96',
                'd': '91',
                'a': '23',
                'diff_k_d': '+5',
                'kast': '67%',
                'adr': '150',
                'hs': '33%',
                'fk': '25',
                'fd': '26',
                'diff_fk_fd': '-1',
              },
              {
                'name': 'Kyu',
                'flag': 'flag-ca',
                'agents': ['Viper', 'Breach', 'Sova', 'Skye'],
                'rating': '0.96',
                'acs': '165',
                'k': '68',
                'd': '78',
                'a': '48',
                'diff_k_d': '-10',
                'kast': '79%',
                'adr': '114',
                'hs': '26%',
                'fk': '5',
                'fd': '7',
                'diff_fk_fd': '-2',
              },
              {
                'name': 'Okeanos',
                'flag': 'flag-vn',
                'agents': ['Fade', 'Sova', 'Yoru', 'Tejo'],
                'rating': '0.86',
                'acs': '176',
                'k': '81',
                'd': '90',
                'a': '30',
                'diff_k_d': '-9',
                'kast': '67%',
                'adr': '111',
                'hs': '28%',
                'fk': '8',
                'fd': '11',
                'diff_fk_fd': '-3',
              },
            ],
          },
          {
            'round': '1',
            'map_name': 'Lotus',
            'map_duration': '54:14',
            'team1_round_score': '10',
            'team2_round_score': '13',
            'team1_stats': [
              {
                'name': 'moobs',
                'flag': 'flag-ca',
                'agents': ['Cypher'],
                'rating': '1.56',
                'acs': '280',
                'k': '22',
                'd': '14',
                'a': '4',
                'diff_k_d': '+8',
                'kast': '61%',
                'adr': '186',
                'hs': '43%',
                'fk': '4',
                'fd': '2',
                'diff_fk_fd': '+2',
              },
              {
                'name': 'Ali',
                'flag': 'flag-ps',
                'agents': ['Clove'],
                'rating': '0.88',
                'acs': '246',
                'k': '19',
                'd': '22',
                'a': '6',
                'diff_k_d': '-3',
                'kast': '70%',
                'adr': '152',
                'hs': '35%',
                'fk': '1',
                'fd': '4',
                'diff_fk_fd': '-3',
              },
              {
                'name': 'Nahsie',
                'flag': 'flag-us',
                'agents': ['Sova'],
                'rating': '0.82',
                'acs': '153',
                'k': '12',
                'd': '16',
                'a': '4',
                'diff_k_d': '-4',
                'kast': '61%',
                'adr': '110',
                'hs': '43%',
                'fk': '1',
                'fd': '0',
                'diff_fk_fd': '+1',
              },
              {
                'name': 'flare',
                'flag': 'flag-vn',
                'agents': ['Tejo'],
                'rating': '0.74',
                'acs': '119',
                'k': '11',
                'd': '15',
                'a': '6',
                'diff_k_d': '-4',
                'kast': '70%',
                'adr': '81',
                'hs': '38%',
                'fk': '0',
                'fd': '0',
                'diff_fk_fd': '0',
              },
              {
                'name': 'infiltrator',
                'flag': 'flag-vn',
                'agents': ['Raze'],
                'rating': '0.60',
                'acs': '162',
                'k': '12',
                'd': '19',
                'a': '4',
                'diff_k_d': '-7',
                'kast': '65%',
                'adr': '106',
                'hs': '20%',
                'fk': '5',
                'fd': '6',
                'diff_fk_fd': '-1',
              },
            ],
            'team2_stats': [
              {
                'name': 'bao',
                'flag': 'flag-vn',
                'agents': ['Vyse'],
                'rating': '1.33',
                'acs': '260',
                'k': '22',
                'd': '14',
                'a': '4',
                'diff_k_d': '+8',
                'kast': '78%',
                'adr': '180',
                'hs': '27%',
                'fk': '4',
                'fd': '4',
                'diff_fk_fd': '0',
              },
              {
                'name': 'Sato',
                'flag': 'flag-br',
                'agents': ['Raze'],
                'rating': '1.30',
                'acs': '291',
                'k': '21',
                'd': '17',
                'a': '6',
                'diff_k_d': '+4',
                'kast': '65%',
                'adr': '202',
                'hs': '33%',
                'fk': '5',
                'fd': '2',
                'diff_fk_fd': '+3',
              },
              {
                'name': 'Okeanos',
                'flag': 'flag-vn',
                'agents': ['Fade'],
                'rating': '1.15',
                'acs': '211',
                'k': '18',
                'd': '15',
                'a': '10',
                'diff_k_d': '+3',
                'kast': '74%',
                'adr': '132',
                'hs': '33%',
                'fk': '2',
                'fd': '0',
                'diff_fk_fd': '+2',
              },
              {
                'name': 'bdog',
                'flag': 'flag-us',
                'agents': ['Omen'],
                'rating': '1.00',
                'acs': '186',
                'k': '14',
                'd': '16',
                'a': '14',
                'diff_k_d': '-2',
                'kast': '78%',
                'adr': '118',
                'hs': '24%',
                'fk': '0',
                'fd': '1',
                'diff_fk_fd': '-1',
              },
              {
                'name': 'Kyu',
                'flag': 'flag-ca',
                'agents': ['Viper'],
                'rating': '0.75',
                'acs': '134',
                'k': '11',
                'd': '14',
                'a': '5',
                'diff_k_d': '-3',
                'kast': '70%',
                'adr': '89',
                'hs': '24%',
                'fk': '1',
                'fd': '4',
                'diff_fk_fd': '-3',
              },
            ],
          },
          {
            'round': '2',
            'map_name': 'Haven',
            'map_duration': '1:11:55',
            'team1_round_score': '15',
            'team2_round_score': '17',
            'team1_stats': [
              {
                'name': 'infiltrator',
                'flag': 'flag-vn',
                'agents': ['Yoru'],
                'rating': '1.15',
                'acs': '235',
                'k': '27',
                'd': '23',
                'a': '7',
                'diff_k_d': '+4',
                'kast': '69%',
                'adr': '149',
                'hs': '25%',
                'fk': '7',
                'fd': '6',
                'diff_fk_fd': '+1',
              },
              {
                'name': 'flare',
                'flag': 'flag-vn',
                'agents': ['Tejo'],
                'rating': '1.06',
                'acs': '220',
                'k': '23',
                'd': '22',
                'a': '8',
                'diff_k_d': '+1',
                'kast': '72%',
                'adr': '160',
                'hs': '28%',
                'fk': '6',
                'fd': '1',
                'diff_fk_fd': '+5',
              },
              {
                'name': 'moobs',
                'flag': 'flag-ca',
                'agents': ['Vyse'],
                'rating': '0.97',
                'acs': '249',
                'k': '27',
                'd': '28',
                'a': '6',
                'diff_k_d': '-1',
                'kast': '63%',
                'adr': '162',
                'hs': '42%',
                'fk': '4',
                'fd': '2',
                'diff_fk_fd': '+2',
              },
              {
                'name': 'Nahsie',
                'flag': 'flag-us',
                'agents': ['Breach'],
                'rating': '0.92',
                'acs': '160',
                'k': '17',
                'd': '20',
                'a': '21',
                'diff_k_d': '-3',
                'kast': '75%',
                'adr': '111',
                'hs': '35%',
                'fk': '0',
                'fd': '4',
                'diff_fk_fd': '-4',
              },
              {
                'name': 'Ali',
                'flag': 'flag-ps',
                'agents': ['Astra'],
                'rating': '0.69',
                'acs': '153',
                'k': '16',
                'd': '24',
                'a': '11',
                'diff_k_d': '-8',
                'kast': '63%',
                'adr': '104',
                'hs': '22%',
                'fk': '0',
                'fd': '2',
                'diff_fk_fd': '-2',
              },
            ],
            'team2_stats': [
              {
                'name': 'bao',
                'flag': 'flag-vn',
                'agents': ['Cypher'],
                'rating': '1.47',
                'acs': '307',
                'k': '36',
                'd': '22',
                'a': '4',
                'diff_k_d': '+14',
                'kast': '81%',
                'adr': '182',
                'hs': '54%',
                'fk': '2',
                'fd': '2',
                'diff_fk_fd': '0',
              },
              {
                'name': 'bdog',
                'flag': 'flag-us',
                'agents': ['Omen'],
                'rating': '1.12',
                'acs': '225',
                'k': '26',
                'd': '22',
                'a': '11',
                'diff_k_d': '+4',
                'kast': '69%',
                'adr': '133',
                'hs': '28%',
                'fk': '4',
                'fd': '5',
                'diff_fk_fd': '-1',
              },
              {
                'name': 'Kyu',
                'flag': 'flag-ca',
                'agents': ['Breach'],
                'rating': '1.04',
                'acs': '185',
                'k': '18',
                'd': '20',
                'a': '14',
                'diff_k_d': '-2',
                'kast': '69%',
                'adr': '136',
                'hs': '25%',
                'fk': '1',
                'fd': '1',
                'diff_fk_fd': '0',
              },
              {
                'name': 'Sato',
                'flag': 'flag-br',
                'agents': ['Neon'],
                'rating': '0.84',
                'acs': '191',
                'k': '19',
                'd': '23',
                'a': '8',
                'diff_k_d': '-4',
                'kast': '66%',
                'adr': '128',
                'hs': '32%',
                'fk': '6',
                'fd': '7',
                'diff_fk_fd': '-1',
              },
              {
                'name': 'Okeanos',
                'flag': 'flag-vn',
                'agents': ['Sova'],
                'rating': '0.81',
                'acs': '142',
                'k': '18',
                'd': '23',
                'a': '7',
                'diff_k_d': '-5',
                'kast': '66%',
                'adr': '96',
                'hs': '39%',
                'fk': '2',
                'fd': '2',
                'diff_fk_fd': '0',
              },
            ],
          },
          {
            'round': '3',
            'map_name': 'Abyss',
            'map_duration': '50:13',
            'team1_round_score': '13',
            'team2_round_score': '8',
            'team1_stats': [
              {
                'name': 'moobs',
                'flag': 'flag-ca',
                'agents': ['Cypher'],
                'rating': '1.29',
                'acs': '252',
                'k': '21',
                'd': '13',
                'a': '4',
                'diff_k_d': '+8',
                'kast': '67%',
                'adr': '160',
                'hs': '55%',
                'fk': '3',
                'fd': '2',
                'diff_fk_fd': '+1',
              },
              {
                'name': 'Nahsie',
                'flag': 'flag-us',
                'agents': ['Sova'],
                'rating': '1.15',
                'acs': '235',
                'k': '16',
                'd': '14',
                'a': '8',
                'diff_k_d': '+2',
                'kast': '71%',
                'adr': '166',
                'hs': '24%',
                'fk': '3',
                'fd': '1',
                'diff_fk_fd': '+2',
              },
              {
                'name': 'flare',
                'flag': 'flag-vn',
                'agents': ['Tejo'],
                'rating': '1.07',
                'acs': '178',
                'k': '14',
                'd': '12',
                'a': '5',
                'diff_k_d': '+2',
                'kast': '71%',
                'adr': '122',
                'hs': '25%',
                'fk': '2',
                'fd': '0',
                'diff_fk_fd': '+2',
              },
              {
                'name': 'infiltrator',
                'flag': 'flag-vn',
                'agents': ['Jett'],
                'rating': '1.06',
                'acs': '199',
                'k': '17',
                'd': '14',
                'a': '2',
                'diff_k_d': '+3',
                'kast': '81%',
                'adr': '123',
                'hs': '18%',
                'fk': '7',
                'fd': '2',
                'diff_fk_fd': '+5',
              },
              {
                'name': 'Ali',
                'flag': 'flag-ps',
                'agents': ['Astra'],
                'rating': '1.06',
                'acs': '158',
                'k': '11',
                'd': '12',
                'a': '10',
                'diff_k_d': '-1',
                'kast': '81%',
                'adr': '101',
                'hs': '29%',
                'fk': '1',
                'fd': '0',
                'diff_fk_fd': '+1',
              },
            ],
            'team2_stats': [
              {
                'name': 'bdog',
                'flag': 'flag-us',
                'agents': ['Omen'],
                'rating': '1.22',
                'acs': '216',
                'k': '16',
                'd': '14',
                'a': '8',
                'diff_k_d': '+2',
                'kast': '62%',
                'adr': '148',
                'hs': '26%',
                'fk': '2',
                'fd': '3',
                'diff_fk_fd': '-1',
              },
              {
                'name': 'bao',
                'flag': 'flag-vn',
                'agents': ['Astra'],
                'rating': '1.04',
                'acs': '204',
                'k': '15',
                'd': '15',
                'a': '4',
                'diff_k_d': '0',
                'kast': '67%',
                'adr': '140',
                'hs': '31%',
                'fk': '2',
                'fd': '0',
                'diff_fk_fd': '+2',
              },
              {
                'name': 'Kyu',
                'flag': 'flag-ca',
                'agents': ['Sova'],
                'rating': '1.03',
                'acs': '150',
                'k': '10',
                'd': '14',
                'a': '9',
                'diff_k_d': '-4',
                'kast': '81%',
                'adr': '115',
                'hs': '31%',
                'fk': '0',
                'fd': '0',
                'diff_fk_fd': '0',
              },
              {
                'name': 'Sato',
                'flag': 'flag-br',
                'agents': ['Jett'],
                'rating': '0.73',
                'acs': '223',
                'k': '16',
                'd': '19',
                'a': '3',
                'diff_k_d': '-3',
                'kast': '57%',
                'adr': '145',
                'hs': '48%',
                'fk': '1',
                'fd': '9',
                'diff_fk_fd': '-8',
              },
              {
                'name': 'Okeanos',
                'flag': 'flag-vn',
                'agents': ['Yoru'],
                'rating': '0.28',
                'acs': '106',
                'k': '8',
                'd': '19',
                'a': '3',
                'diff_k_d': '-11',
                'kast': '48%',
                'adr': '57',
                'hs': '25%',
                'fk': '0',
                'fd': '4',
                'diff_fk_fd': '-4',
              },
            ],
          },
          {
            'round': '4',
            'map_name': 'Pearl',
            'map_duration': '58:54',
            'team1_round_score': '13',
            'team2_round_score': '11',
            'team1_stats': [
              {
                'name': 'moobs',
                'flag': 'flag-ca',
                'agents': ['Vyse'],
                'rating': '1.31',
                'acs': '286',
                'k': '26',
                'd': '18',
                'a': '3',
                'diff_k_d': '+8',
                'kast': '71%',
                'adr': '170',
                'hs': '41%',
                'fk': '2',
                'fd': '4',
                'diff_fk_fd': '-2',
              },
              {
                'name': 'flare',
                'flag': 'flag-vn',
                'agents': ['Tejo'],
                'rating': '1.02',
                'acs': '157',
                'k': '14',
                'd': '15',
                'a': '4',
                'diff_k_d': '-1',
                'kast': '71%',
                'adr': '114',
                'hs': '32%',
                'fk': '2',
                'fd': '1',
                'diff_fk_fd': '+1',
              },
              {
                'name': 'Ali',
                'flag': 'flag-ps',
                'agents': ['Astra'],
                'rating': '0.94',
                'acs': '169',
                'k': '15',
                'd': '16',
                'a': '7',
                'diff_k_d': '-1',
                'kast': '79%',
                'adr': '110',
                'hs': '33%',
                'fk': '0',
                'fd': '3',
                'diff_fk_fd': '-3',
              },
              {
                'name': 'infiltrator',
                'flag': 'flag-vn',
                'agents': ['Jett'],
                'rating': '0.89',
                'acs': '159',
                'k': '13',
                'd': '16',
                'a': '1',
                'diff_k_d': '-3',
                'kast': '67%',
                'adr': '92',
                'hs': '31%',
                'fk': '5',
                'fd': '3',
                'diff_fk_fd': '+2',
              },
              {
                'name': 'Nahsie',
                'flag': 'flag-us',
                'agents': ['Fade'],
                'rating': '0.82',
                'acs': '197',
                'k': '14',
                'd': '19',
                'a': '9',
                'diff_k_d': '-5',
                'kast': '83%',
                'adr': '132',
                'hs': '26%',
                'fk': '1',
                'fd': '3',
                'diff_fk_fd': '-2',
              },
            ],
            'team2_stats': [
              {
                'name': 'bao',
                'flag': 'flag-vn',
                'agents': ['Killjoy'],
                'rating': '1.20',
                'acs': '242',
                'k': '21',
                'd': '17',
                'a': '5',
                'diff_k_d': '+4',
                'kast': '83%',
                'adr': '164',
                'hs': '30%',
                'fk': '1',
                'fd': '1',
                'diff_fk_fd': '0',
              },
              {
                'name': 'Sato',
                'flag': 'flag-br',
                'agents': ['Jett'],
                'rating': '1.03',
                'acs': '189',
                'k': '16',
                'd': '15',
                'a': '4',
                'diff_k_d': '+1',
                'kast': '75%',
                'adr': '123',
                'hs': '43%',
                'fk': '5',
                'fd': '5',
                'diff_fk_fd': '0',
              },
              {
                'name': 'Okeanos',
                'flag': 'flag-vn',
                'agents': ['Fade'],
                'rating': '0.98',
                'acs': '235',
                'k': '21',
                'd': '19',
                'a': '3',
                'diff_k_d': '+2',
                'kast': '71%',
                'adr': '147',
                'hs': '30%',
                'fk': '4',
                'fd': '0',
                'diff_fk_fd': '+4',
              },
              {
                'name': 'Kyu',
                'flag': 'flag-ca',
                'agents': ['Skye'],
                'rating': '0.84',
                'acs': '165',
                'k': '13',
                'd': '15',
                'a': '9',
                'diff_k_d': '-2',
                'kast': '92%',
                'adr': '102',
                'hs': '25%',
                'fk': '1',
                'fd': '2',
                'diff_fk_fd': '-1',
              },
              {
                'name': 'bdog',
                'flag': 'flag-us',
                'agents': ['Astra'],
                'rating': '0.80',
                'acs': '146',
                'k': '13',
                'd': '16',
                'a': '13',
                'diff_k_d': '-3',
                'kast': '71%',
                'adr': '81',
                'hs': '34%',
                'fk': '3',
                'fd': '2',
                'diff_fk_fd': '+1',
              },
            ],
          },
          {
            'round': '5',
            'map_name': 'Fracture',
            'map_duration': '49:31',
            'team1_round_score': '11',
            'team2_round_score': '13',
            'team1_stats': [
              {
                'name': 'Ali',
                'flag': 'flag-ps',
                'agents': ['Brimstone'],
                'rating': '1.28',
                'acs': '227',
                'k': '19',
                'd': '17',
                'a': '8',
                'diff_k_d': '+2',
                'kast': '71%',
                'adr': '168',
                'hs': '32%',
                'fk': '1',
                'fd': '1',
                'diff_fk_fd': '0',
              },
              {
                'name': 'flare',
                'flag': 'flag-vn',
                'agents': ['Tejo'],
                'rating': '0.97',
                'acs': '192',
                'k': '18',
                'd': '17',
                'a': '6',
                'diff_k_d': '+1',
                'kast': '75%',
                'adr': '156',
                'hs': '20%',
                'fk': '1',
                'fd': '2',
                'diff_fk_fd': '-1',
              },
              {
                'name': 'Nahsie',
                'flag': 'flag-us',
                'agents': ['Breach'],
                'rating': '0.85',
                'acs': '156',
                'k': '11',
                'd': '19',
                'a': '16',
                'diff_k_d': '-8',
                'kast': '75%',
                'adr': '105',
                'hs': '20%',
                'fk': '0',
                'fd': '1',
                'diff_fk_fd': '-1',
              },
              {
                'name': 'moobs',
                'flag': 'flag-ca',
                'agents': ['Cypher'],
                'rating': '0.75',
                'acs': '205',
                'k': '17',
                'd': '22',
                'a': '3',
                'diff_k_d': '-5',
                'kast': '58%',
                'adr': '135',
                'hs': '30%',
                'fk': '5',
                'fd': '1',
                'diff_fk_fd': '+4',
              },
              {
                'name': 'infiltrator',
                'flag': 'flag-vn',
                'agents': ['Raze'],
                'rating': '0.50',
                'acs': '146',
                'k': '12',
                'd': '20',
                'a': '4',
                'diff_k_d': '-8',
                'kast': '58%',
                'adr': '103',
                'hs': '23%',
                'fk': '5',
                'fd': '7',
                'diff_fk_fd': '-2',
              },
            ],
            'team2_stats': [
              {
                'name': 'bdog',
                'flag': 'flag-us',
                'agents': ['Brimstone'],
                'rating': '1.34',
                'acs': '249',
                'k': '20',
                'd': '15',
                'a': '21',
                'diff_k_d': '+5',
                'kast': '92%',
                'adr': '163',
                'hs': '33%',
                'fk': '2',
                'fd': '3',
                'diff_fk_fd': '-1',
              },
              {
                'name': 'Sato',
                'flag': 'flag-br',
                'agents': ['Raze'],
                'rating': '1.20',
                'acs': '274',
                'k': '24',
                'd': '17',
                'a': '2',
                'diff_k_d': '+7',
                'kast': '71%',
                'adr': '161',
                'hs': '19%',
                'fk': '8',
                'fd': '3',
                'diff_fk_fd': '+5',
              },
              {
                'name': 'Kyu',
                'flag': 'flag-ca',
                'agents': ['Breach'],
                'rating': '1.10',
                'acs': '191',
                'k': '16',
                'd': '15',
                'a': '11',
                'diff_k_d': '+1',
                'kast': '88%',
                'adr': '121',
                'hs': '27%',
                'fk': '2',
                'fd': '0',
                'diff_fk_fd': '+2',
              },
              {
                'name': 'Okeanos',
                'flag': 'flag-vn',
                'agents': ['Tejo'],
                'rating': '1.03',
                'acs': '186',
                'k': '16',
                'd': '14',
                'a': '7',
                'diff_k_d': '+2',
                'kast': '75%',
                'adr': '124',
                'hs': '14%',
                'fk': '0',
                'fd': '5',
                'diff_fk_fd': '-5',
              },
              {
                'name': 'bao',
                'flag': 'flag-vn',
                'agents': ['Vyse'],
                'rating': '0.97',
                'acs': '152',
                'k': '14',
                'd': '16',
                'a': '10',
                'diff_k_d': '-2',
                'kast': '88%',
                'adr': '99',
                'hs': '11%',
                'fk': '0',
                'fd': '1',
                'diff_fk_fd': '-1',
              },
            ],
          },
        ],
      },
    ],
  },
};
